elastic_authen:
  host: 
  scheme: 
  user: 
  password: 
  index_name: 
kibana:
  host: 
  scheme: 
  user: 
  password: 
file:
  list_url: 
  rule_file: 
  list_iocs_folder: 
  new_hash: 
  old_hash: 
  output_dir: 
  siem_outfile: 
  sigma_folder: 
network:
  elastic_dection_api: api/detection_engine/rules?overwrite=true
  elastic_check_api: api/detection_engine/rules?id =
  proxy_http:
  proxy_https:
