elastic_authen:
  host: #Elastic host ip (192.168.0.1)
  scheme: #Elastic scheme (https or http)
  user: #ELastic user
  password: #Password
  index_name: #Index to manage iocs
file:
  list_url: #File contain list of url to download iocs folder or git repo
  list_iocs_folder: #Folder to contain all iocs
  new_hash: #File contain new hash of all file
  old_hash: #File contain old hash
  output_dir: #Folder where result goes
network:
  proxy_http: 
  proxy_https:
